sudo: required

services:
  - docker

env:
  matrix:
    - TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/[^12]*.t"
    - TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/1*.t"
    - TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/2*.t"
    - TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/[^t]*"
    - TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/t*"
    - TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/*/t"
    - TEST_COMMAND="phpunit"

install:
  - docker build -t mt .

before_script:
  # Skip failed test.
  - rm plugins/MultiBlog/t/02.tags.t

script:
  - docker run -t -v $PWD:/root/movabletype -w /root/movabletype mt bash -c "find /var/lib/mysql -type f | xargs touch && service mysql start && service memcached start && $TEST_COMMAND"

notifications:
  slack:
    secure: c11SdzxeFF23AlZS7b8jeCL8CJSn2Ire6ovAneFwHUUxb9jeG9lqC78mOJiE0Yrcdkv7beom4WVYrFY7ZoT+tD5RXNUkh8PcxPPXBFjvfDi5PCXwbNs1wb4Pa4bHAZvABgjCN8+21KQ6GcvlHl6sDQmhy/8v4yeYngOavsYfhMs=
