dist: precise

language: perl
perl:
  - 5.18

env:
  matrix:
    - TEST_COMMAND="prove -Mlocal::lib -j4 -PMySQLPool=MT::Test::Env -It/lib t/[^12]*.t"
    - TEST_COMMAND="prove -Mlocal::lib -j4 -PMySQLPool=MT::Test::Env -It/lib t/1*.t"
    - TEST_COMMAND="prove -Mlocal::lib -j4 -PMySQLPool=MT::Test::Env -It/lib t/2*.t"
    - TEST_COMMAND="prove -Mlocal::lib -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/[^t]*"
    - TEST_COMMAND="prove -Mlocal::lib -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/t*"
    - TEST_COMMAND="prove -Mlocal::lib -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/*/t"
    - TEST_COMMAND="./phpunit"

services:
  - memcached

addons:
  apt_packages:
    - libgd2-xpm-dev
    - libgmp3-dev
    - libperl-dev
    - php5
    - php5-cli
    - php5-mysql
    - php5-gd
    - php5-memcache
    - libpng12-dev
    - libgif-dev
    - libjpeg-dev
    - cpanminus
    - perlmagick
    - zip
    - unzip

before_install:
  # Use PHPUnit 4.8, because PHP version of Travis CI is 5.3.
  - wget -O phpunit https://phar.phpunit.de/phpunit-old.phar
  - chmod +x phpunit

install:
  # Update to install Math::GMP2.11.
  - cpanm --self-upgrade

  # Tests fail with Perl 5.10.
  - cpanm -l --notest --quiet XML::Parser::PerlSAX

  # Use to install patched Coro.
  - cpanm -l --notest --quiet LWP::Protocol::https

  # Use patched Coro for Perl 5.22.
  - cpanm -l --notest --quiet https://github.com/rurban/Coro/archive/rel-6.48_01.tar.gz

  # Tests fail with Perl 5.8 and 5.10.
  - cpanm -l --notest --quiet Twiggy

  # Cannot install Math::GMP 2.12 and 2.13 with Perl 5.8.
  - cpanm -l --notest --quiet Math::GMP@2.11

  - cpanm -l --notest App::cpm

  # Instal CPAN modules.
  - cp ./t/cpanfile .
  - travis_retry cpm install -l

  # Build MT.
  #- SHELL=/bin/bash make me

before_script:
  # Create MySQL database for tests.
  - mysql -e "create database mt_test;"
  - mysql -uroot -e "grant all privileges on mt_test.* to mt@localhost;"

  # Some tests need mt-config.cgi.
  - cp ./t/mysql-test.cfg ./mt-config.cgi

  # Skip failed test.
  - rm plugins/MultiBlog/t/02.tags.t

script:
  - bash -c "${TEST_COMMAND}"

notifications:
  slack:
    secure: c11SdzxeFF23AlZS7b8jeCL8CJSn2Ire6ovAneFwHUUxb9jeG9lqC78mOJiE0Yrcdkv7beom4WVYrFY7ZoT+tD5RXNUkh8PcxPPXBFjvfDi5PCXwbNs1wb4Pa4bHAZvABgjCN8+21KQ6GcvlHl6sDQmhy/8v4yeYngOavsYfhMs=
