sudo: required

services:
  - docker

env:
  matrix:
    - PERL_VERSION="5.10" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/[^12]*.t"
    - PERL_VERSION="5.10" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/1*.t"
    - PERL_VERSION="5.10" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/2*.t"
    - PERL_VERSION="5.10" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/[^t]*"
    - PERL_VERSION="5.10" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/t*"
    - PERL_VERSION="5.10" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/*/t"
    - PERL_VERSION="5.10" TEST_COMMAND="phpunit"

    - PERL_VERSION="5.18" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/[^12]*.t"
    - PERL_VERSION="5.18" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/1*.t"
    - PERL_VERSION="5.18" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/2*.t"
    - PERL_VERSION="5.18" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/[^t]*"
    - PERL_VERSION="5.18" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/t*"
    - PERL_VERSION="5.18" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/*/t"
    - PERL_VERSION="5.18" TEST_COMMAND="phpunit"

    - PERL_VERSION="5.24" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/[^12]*.t"
    - PERL_VERSION="5.24" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/1*.t"
    - PERL_VERSION="5.24" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/2*.t"
    - PERL_VERSION="5.24" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/[^t]*"
    - PERL_VERSION="5.24" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/mt7/t*"
    - PERL_VERSION="5.24" TEST_COMMAND="prove -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/*/t"
    - PERL_VERSION="5.24" TEST_COMMAND="phpunit"

install:
  - if [ "$PERL_VERSION" = "5.10" ] || [ "$PERL_VERSION" = "5.24" ]; then cp -f Dockerfile.perl-$PERL_VERSION Dockerfile; fi
  - if [ $TRAVIS_BRANCH = "master" ] || [ $TRAVIS_BRANCH = "develop" ] || ([ "$PERL_VERSION" != "5.10" ] && [ "$PERL_VERSION" != "5.24" ]); then docker build -t mt .; fi

before_script:
  # Skip failed test.
  - rm plugins/MultiBlog/t/02.tags.t

script:
  - if ([ $TRAVIS_BRANCH = "master" ] || [ $TRAVIS_BRANCH = "develop" ] || [ "$PERL_VERSION" != "5.24" ]) && [ "$PERL_VERSION" != "5.10" ]; then docker run -t -v $PWD:/root/movabletype -w /root/movabletype mt bash -c "find /var/lib/mysql -type f | xargs touch && service mysql start && service memcached start && $TEST_COMMAND"; fi
  - if ([ $TRAVIS_BRANCH = "master" ] || [ $TRAVIS_BRANCH = "develop" ]) && [ "$PERL_VERSION" = "5.10" ]; then docker run -t -v $PWD:/root/movabletype -w /root/movabletype mt bash -c "service mysqld start && service memcached start && $TEST_COMMAND"; fi

notifications:
  slack:
    secure: c11SdzxeFF23AlZS7b8jeCL8CJSn2Ire6ovAneFwHUUxb9jeG9lqC78mOJiE0Yrcdkv7beom4WVYrFY7ZoT+tD5RXNUkh8PcxPPXBFjvfDi5PCXwbNs1wb4Pa4bHAZvABgjCN8+21KQ6GcvlHl6sDQmhy/8v4yeYngOavsYfhMs=
