version: 2
jobs:
  coveralls:
    docker:
      - image: masiuchi/docker-mt-test:trusty-full
    steps:
      - checkout
      - run: cpm install -g Devel::Cover::Report::Coveralls
      - run: bash /docker-entrypoint.sh echo 'run docker-entrypoint.sh'
      - run:
          name: Test and send coverage report
          command: |
            HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,^extlib,+ignore,^t prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/class/80-serialize-leak.t
            cover -report coveralls

workflows:
   version: 2
   normal_test_workflow:
     jobs:
       - coveralls
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - develop
     jobs:
       - coveralls

