version: 2
jobs:
  coveralls:
    docker:
      - image: masiuchi/docker-mt-test:trusty-full
    steps:
      - checkout
      - run: COVERALLS_REPO_TOKEN= cpm install -g --test Devel::Cover::Report::Coveralls
      - run: bash /docker-entrypoint.sh HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,^extlib,+ignore,^t prove -j4 -PMySQLPool=MT::Test::Env -It/lib t plugins/*/t
      - run: cover -port coveralls

workflows:
   version: 2
   normal_test_workflow:
     jobs:
       - coveralls
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - develop
     jobs:
       - coveralls

